(*
 * FileName:   paslib.inc
 * $Source: E:/usr/src/c-code/pascal/RCS/LIB/paslib.inc,v $
 * $Author: wjw $
 * $Date: 1993/11/03 15:54:58 $
 * $Locker: wjw $
 * $State: Exp $
 * $Revision: 1.1 $
 * Description:
 *      Part of the runtime library which comes with PASCAL for OS/2
 *      
 *
 * History:
 *      First created by Willem Jan Withagen ( wjw@eb.ele.tue.nl ),
 *                    on Mon July 26 23:30:03 MET 1993
 * Copyright:
 *      Copyright (c) 1993 by Willem Jan Withagen and 
 *                      Digital Information Systems group, TUE
 *      For copying and distribution information see the file COPYRIGHT.
 *
 *)
(* Items which are supported by the runtime lib
(* But are not actual contained in the compiler.
 *)
procedure wrtoke; external;
procedure wrtwrong; external;
